# Generated by Django 3.2.9 on 2021-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('since', models.IntegerField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('about', models.TextField()),
                ('logo', models.FileField(upload_to='')),
                ('profile_pdf', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
