# Generated by Django 3.2.9 on 2021-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_auto_20211110_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
