# Generated by Django 3.2.9 on 2021-11-12 09:39

from django.db import migrations, models
import webApp.models.company_profile


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0013_auto_20211111_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(null=True, upload_to=webApp.models.company_profile.create_path_logo),
        ),
    ]
