# Generated by Django 3.2.9 on 2021-11-12 14:10

from django.db import migrations, models
import webApp.models.gallery_image


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=webApp.models.gallery_image.create_path_gallery_image)),
                ('thumbnail', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
