# Generated by Django 3.2.9 on 2022-03-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
