# Generated by Django 3.2.9 on 2022-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0017_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='project',
            name='started',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
