# Generated by Django 3.2.9 on 2022-03-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0019_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(default='Civil Engineering', max_length=100),
        ),
    ]
