# Generated by Django 3.2.9 on 2023-03-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0020_alter_galleryimage_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-year'], 'verbose_name_plural': 'Projects'},
        ),
    ]
