# Generated by Django 3.2.9 on 2023-03-13 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0021_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
